services:
  main-initialize:
    image: alpine:latest
    env_file:
      - stack.env
    environment:
      ENVSE1:
      ENVSE2:
      ENVPE1: "${ENVPE1}"
      ENVPE2:
      ENVPE3:
      ENVDC1: "OU=Users,OU=bimbo"
    entrypoint: ["/bin/sh", "-c"]
    command: ['printenv; echo "compose: ENVSE1=${ENVSE1}"; echo "ENVSE2=${ENVSE2}"; echo "ENVSE3=${ENVSE3}"; echo "ENVPE1=${ENVPE1}"; echo "ENVPE2=${ENVPE2}"; echo "ENVPE3=${ENVPE3}"; echo "ENVDC1=${ENVDC1}";']
