services:
  main-initialize:
    image: alpine:latest
    env_file:
      - stack.env
    environment:
      ENV1:
      ENV2:
      ENV3: "${ENV3}"
      ENV4: "OU=Users,OU=bimbo"
    entrypoint: ["/bin/sh", "-c"]
    command: ['printenv']
