services:
  main-initialize:
    image: alpine:latest
    env_file:
      - stack.env
    environment:
      ENV1:
      ENV2:
    entrypoint: ["/bin/sh", "-xvc"]
    command: ['printenv;echo ENV1=${ENV1};echo ENV2=${ENV2};printenv']
