services:
  main-initialize:
    image: alpine:latest
    env_file:
      - stack.env
    environment:
      ENVSE1:
      ENVSE2:
      ENVPE1: 
      ENVPE2: "${ENVPE2}"
      ENVPE3:
      ENVDC1: "OU=Users,OU=bimbo"
    entrypoint: ["/bin/sh", "-xvc"]
    command: ['printenv; echo "compose: ENVSE1=${ENVSE1} ENVSE2=${ENVSE2} ENVSE3=${ENVSE3} ENVPE1=${ENVPE1} ENVPE2=${ENVPE2} ENVPE3=${ENVPE3} ENVDC1=${ENVDC1}";']
