services:
  main-initialize:
    image: alpine:latest
    env_file:
      - stack.env
    environment:
      ENVSE1:
      ENVSE2:
      ENVPE3: "${ENVPE1}"
      ENVPE2:
      ENVDC1: "OU=Users,OU=bimbo"
    entrypoint: ["/bin/sh", "-c"]
    command: ['printenv; echo "ENVSE1=${ENVSE1}"; echo "ENVSE2=${ENVSE2}"; echo "ENVSE3=${ENVSE3}"; echo "ENVPE3=${ENVPE1}"; echo "ENVPE4=${ENVPE2}"; echo "ENVDC5=${ENVDC1}";']
