services:
  main-initialize:
    image: alpine:latest
    env_file:
      - stack.env
    environment:
      ENV1:
      ENV2:
    entrypoint: ["/bin/sh", "-xvc"]
    command: ["echo ENV1=${ENV1} ENV2=${ENV2};printenv"]
