secrets:
  very_secret:
    file: ${EIAB_EXTRA:-.}/secrets/very_secret.txt
services:
  main-initialize:
    image: alpine:latest
    env_file:
      - ${EIAB_APP:+/image-build/eiab/tse}${EIAB_ENV:+.}/env/${EIAB_ENV:-prod}.env
    environment:
      env_stack_env1: "${env_stack_env1}"
      env_stack_env2:
      env_comp1: 
      env_env1:
      env_env2: "${env_env2}"
      env_comp3:
      env_root_stack2: "${env_root_stack2}"
      env_compdc1: "OU=Users,OU=compose"
    entrypoint: ["/bin/sh", "-xvc"]
    secrets:
      - very_secret
    volumes:
      - ${EIAB_APP:-.}/vols/scripts:/scripts
      - ${EIAB_EXTRA:-.}/vols/extras:/extras
    command: ['printenv; echo "compose: env_stack_env1=${env_stack_env1} env_stack_env2=${env_stack_env2} env_stack_env3=${env_stack_env3} env_comp1=${env_comp1} env_env2=${env_env2} env_comp3=${env_comp3} env_compdc1=${env_compdc1}";ls -l /scripts /extras;
      echo "very_secret: $(cat /run/secrets/very_secret)"; echo "compose: EIAB_APP=${EIAB_APP} EIAB_ENV=${EIAB_ENV} EIAB_EXTRA=${EIAB_EXTRA}"']
