x-my-env: &my-env
  env1:
  env2:
services:
  main-initialize:
    image: alpine:latest
#    env_file:
#      - stack.env
    environment:
      <<: *my-env
    entrypoint: ["/bin/sh", "-c"]
    command: ["echo env1=${env1};printenv"]
